//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Web;

    public class SystemDocumentation
    {
        public int doc_id { get; set; }

        [DisplayName("Upload File")]
        public string img_url { get; set; }
        public string description { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
