//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int donId { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> donDate { get; set; }
        public string donType { get; set; }
        public Nullable<decimal> donAmount { get; set; }
        public string itemDescription { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
    }
}
